[env:esp32-s3-camera]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200
upload_speed = 460800

board_build.flash_size = 16MB
board_build.partitions = default_8MB.csv

board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = qio

build_flags =
  -D ARDUINO_USB_CDC_ON_BOOT=0
  -D BOARD_HAS_PSRAM
  -D CONFIG_SPIRAM_SUPPORT=1

lib_deps =
  knolleary/PubSubClient@^2.8
  bblanchon/ArduinoJson@^7.0.4